apiVersion: v1
kind: ReplicationController
metadata:
  name: sinusbot-v0.9.11-ee30ef7
  namespace: default
  labels:
    version: v0.9.11-ee30ef7
    app: sinusbot
spec:
  replicas: 1
  selector:
    version: v0.9.11-ee30ef7
    app: sinusbot
  template:
    metadata:
      labels:
        app: sinusbot
        version: v0.9.11-ee30ef7
    spec:
      containers:
        - image: xeronick/sinusbot-beta:latest
          name: sinusbot
          resources:
            limits:
              cpu: 50m
              memory: 768Mi
          ports:
            - containerPort: 8087
              hostPort: 8087
              protocol: TCP
          volumeMounts:
          - name: sinusbot-persistent-storage
            mountPath: /sinusbot/data
            readOnly: false
      volumes:
      - name: sinusbot-persistent-storage
        hostPath:
          path: /container-data/sinusbot-data
